=== Doriane-Richard/JEU_TRIVIAL_PURSUIT_REMASTER_RICHARD_OURAHA_SADIKI/xsd/Cartes.xsd
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           targetNamespace="http://www.univ-grenoble-alpes.fr/l3miage/trivialpursuit"
           xmlns:tp="http://www.univ-grenoble-alpes.fr/l3miage/trivialpursuit"
           elementFormDefault="qualified">

    <!--  Cartes element racine -->
    <xs:element name="Cartes">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="Carte" type="tp:Carte" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
        
        <!-- UnicitÃ© pour l'id de la carte -->
        <xs:key name="CarteIdUnique">
            <xs:selector xpath="tp:Carte"/>
            <xs:field xpath="@id"/>
        </xs:key>
    </xs:element>
    
    
    <!-- Carte -->
    <xs:complexType name="Carte">
        <xs:sequence>
            <xs:element name="Question" type="xs:string"/>
            <xs:element name="Reponses" type="tp:Reponses"/>
        </xs:sequence>
        <xs:attribute name="id" type="xs:int" use="required"/>
        <xs:attribute name="difficulte" type="tp:Difficulte" use="required"/>
        <xs:attribute name="categorieId" type="xs:int" use="required"/>
    </xs:complexType>

    <!-- Reponses -->
    <xs:complexType name="Reponses">
        <xs:sequence>
            <xs:element name="Reponse" type="tp:Reponse" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <!-- Reponse -->
    <xs:complexType name="Reponse">
        <xs:attribute name="id" type="xs:int" use="required"/>
        <xs:attribute name="texte" type="xs:string" use="required"/>
        <xs:attribute name="correct" type="xs:boolean" use="required"/>
    </xs:complexType>

    <!--  Difficulte -->
    <xs:simpleType name="Difficulte">
        <xs:restriction base="xs:string">
            <xs:enumeration value="Facile"/>
            <xs:enumeration value="Moyen"/>
            <xs:enumeration value="Difficile"/>
        </xs:restriction>
    </xs:simpleType>

</xs:schema>

=== Doriane-Richard/JEU_TRIVIAL_PURSUIT_REMASTER_RICHARD_OURAHA_SADIKI/xml/Cartes.xml
<?xml version="1.0" encoding="utf-8"?>
<Cartes xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
        xmlns:xsd="http://www.w3.org/2001/XMLSchema" 
        xsi:schemaLocation="http://www.univ-grenoble-alpes.fr/l3miage/trivialpursuit ../xsd/Cartes.xsd" 
        xmlns="http://www.univ-grenoble-alpes.fr/l3miage/trivialpursuit">
    
    <!-- Zythologie facile -->
    <Carte id="101" difficulte="Facile" categorieId="1">
        <Question>Quel est le principal ingrédient de la bière ?</Question>
        <Reponses>
            <Reponse id="1" texte="Orge" correct="true"/>
            <Reponse id="2" texte="Blé" correct="false"/>
            <Reponse id="3" texte="Maïs" correct="false"/>
            <Reponse id="4" texte="Riz" correct="false"/>
        </Reponses>
    </Carte>

    <Carte id="102" difficulte="Facile" categorieId="1">
        <Question>Quel est le nom du processus où les levures transforment le sucre en alcool dans la bière ?</Question>
        <Reponses>
            <Reponse id="1" texte="Fermentation" correct="true"/>
            <Reponse id="2" texte="Distillation" correct="false"/>
            <Reponse id="3" texte="Macération" correct="false"/>
            <Reponse id="4" texte="Filtration" correct="false"/>
        </Reponses>
    </Carte>

    <Carte id="103" difficulte="Facile" categorieId="1">
        <Question>Quel type de bière est généralement plus foncé et plus riche en saveur ?</Question>
        <Reponses>
            <Reponse id="1" texte="Stout" correct="true"/>
            <Reponse id="2" texte="Lager" correct="false"/>
            <Reponse id="3" texte="Pilsner" correct="false"/>
            <Reponse id="4" texte="Blonde" correct="false"/>
        </Reponses>
    </Carte>

    <Carte id="104" difficulte="Facile" categorieId="1">
        <Question>Quel pays est célèbre pour ses bières trappistes ?</Question>
        <Reponses>
            <Reponse id="1" texte="Belgique" correct="true"/>
            <Reponse id="2" texte="Allemagne" correct="false"/>
            <Reponse id="3" texte="République " correct="false"/>
            <Reponse id="4" texte="Tchèque" correct="false"/>
            <Reponse id="5" texte="Pays-Bas" correct="false"/>
        </Reponses>
    </Carte>


    <!-- Zythologie moyen -->

    <Carte id="105" difficulte="Moyen" categorieId="1">
        <Question>Quel type de levure est utilisé pour les bières de type ale ?</Question>
        <Reponses>
            <Reponse id="1" texte="Levure haute" correct="true"/>
            <Reponse id="2" texte="Levure basse" correct="false"/>
            <Reponse id="3" texte="Levure sauvage " correct="false"/>
            <Reponse id="4" texte="Levure sèche" correct="false"/>
        </Reponses>
    </Carte>

    <Carte id="106" difficulte="Moyen" categorieId="1">
        <Question>Quel est le nom du récipient utilisé pour la fermentation de la bière ?</Question>
        <Reponses>
            <Reponse id="1" texte="Cuve de fermentation" correct="true"/>
            <Reponse id="2" texte="Alambic" correct="false"/>
            <Reponse id="3" texte="Fût" correct="false"/>
            <Reponse id="4" texte="Tonneau" correct="false"/>
        </Reponses>
    </Carte>

    <Carte id="107" difficulte="Moyen" categorieId="1">
        <Question>Quel type de bière est souvent associé à la ville de Munich ?</Question>
        <Reponses>
            <Reponse id="1" texte="Weizen" correct="true"/>
            <Reponse id="2" texte="Porter" correct="false"/>
            <Reponse id="3" texte="IPA" correct="false"/>
            <Reponse id="4" texte="Lambic" correct="false"/>
        </Reponses>
    </Carte>

    <Carte id="108" difficulte="Moyen" categorieId="1">
        <Question>Quel est le nom du processus qui consiste à ajouter du houblon à la bière ?</Question>
        <Reponses>
            <Reponse id="1" texte="Houblonnage" correct="true"/>
            <Reponse id="2" texte="Maltage" correct="false"/>
            <Reponse id="3" texte="Brassage" correct="false"/>
            <Reponse id="4" texte="Filtration" correct="false"/>
        </Reponses>
    </Carte>

    <!-- Zythologie difficile -->
    <Carte id="109" difficulte="Difficile" categorieId="1">
        <Question>Quel est le nom du composé chimique responsable de l'amertume dans la bière ?</Question>
        <Reponses>
            <Reponse id="1" texte="Lupuline" correct="true"/>
            <Reponse id="2" texte="Maltose" correct="false"/>
            <Reponse id="3" texte="Dextrine" correct="false"/>
            <Reponse id="4" texte="Isomérisation" correct="false"/>
        </Reponses>
    </Carte>

    <Carte id="110" difficulte="Difficile" categorieId="1">
        <Question>Quel type de bière est traditionnellement brassé avec des fruits ?</Question>
        <Reponses>
            <Reponse id="1" texte="Lambic" correct="true"/>
            <Reponse id="2" texte="Pilsner" correct="false"/>
            <Reponse id="3" texte="Stout" correct="false"/>
            <Reponse id="4" texte="Lager" correct="false"/>
        </Reponses>
    </Carte>

    <Carte id="111" difficulte="Difficile" categorieId="1">
        <Question>Quel est le nom du processus de vieillissement de la bière en fût de chêne ?</Question>
        <Reponses>
            <Reponse id="1" texte="Vieillissement en fût" correct="true"/>
            <Reponse id="2" texte="Carbonatation" correct="false"/>
            <Reponse id="3" texte="Pasteurisation" correct="false"/>
            <Reponse id="4" texte="Clarification" correct="false"/>
        </Reponses>
    </Carte>

    <Carte id="112" difficulte="Difficile" categorieId="1">
        <Question>Quel est le nom de la bière traditionnelle japonaise ?</Question>
        <Reponses>
            <Reponse id="1" texte="Sake" correct="true"/>
            <Reponse id="2" texte="Asahi" correct="false"/>
            <Reponse id="3" texte="Kirin" correct="false"/>
            <Reponse id="4" texte="Sapporo" correct="false"/>
        </Reponses>
    </Carte>

    <!-- Histoire facile -->
    <Carte id="113" difficulte="Facile" categorieId="2">
        <Question>Qui a découvert l'Amérique en 1492 ?</Question>
        <Reponses>
            <Reponse id="1" texte="Christophe Colomb" correct="true"/>
            <Reponse id="2" texte="Amerigo Vespucci" correct="false"/>
            <Reponse id="3" texte="Ferdinand Magellan" correct="false"/>
            <Reponse id="4" texte="Vasco de Gama" correct="false"/>
        </Reponses>
    </Carte>

    <Carte id="114" difficulte="Facile" categorieId="2">
        <Question>Quel était le nom du premier président des États-Unis ?</Question>
        <Reponses>
            <Reponse id="1" texte="George Washington" correct="true"/>
            <Reponse id="2" texte="Thomas Jefferson" correct="false"/>
            <Reponse id="3" texte="John Adams" correct="false"/>
            <Reponse id="4" texte="James Madison" correct="false"/>
        </Reponses>
    </Carte>

    <Carte id="214" difficulte="Facile" categorieId="2">
        <Question>Qui était le premier empereur romain ?</Question>
        <Reponses>
            <Reponse id="1" texte="Auguste" correct="true"/>
            <Reponse id="2" texte="Jules César" correct="false"/>
            <Reponse id="3" texte="Néron" correct="false"/>
            <Reponse id="4" texte="Caligula" correct="false"/>
        </Reponses>
    </Carte>


    <Carte id="215" difficulte="Facile" categorieId="2">
        <Question>En quelle année a eu lieu la révolution française ?</Question>
        <Reponses>
            <Reponse id="1" texte="1789" correct="true"/>
            <Reponse id="2" texte="1776" correct="false"/>
            <Reponse id="3" texte="1848" correct="false"/>
            <Reponse id="4" texte="1917" correct="false"/>
        </Reponses>
    </Carte>


    <!-- Histoire moyen -->

    <Carte id="115" difficulte="Moyen" categorieId="2">
        <Question>Quel traité a mis fin à la Première Guerre mondiale ?</Question>
        <Reponses>
            <Reponse id="1" texte="Traité de Versailles" correct="true"/>
            <Reponse id="2" texte="Traité de Trianon" correct="false"/>
            <Reponse id="3" texte="Traité de Sèvres" correct="false"/>
            <Reponse id="4" texte="Traité de Saint-Germain" correct="false"/>
        </Reponses>
    </Carte>

    <Carte id="116" difficulte="Moyen" categorieId="2">
        <Question>Qui était le leader de la révolution cubaine en 1959 ?</Question>
        <Reponses>
            <Reponse id="1" texte="Fidel Castro" correct="true"/>
            <Reponse id="2" texte="Che Guevara" correct="false"/>
            <Reponse id="3" texte="Raúl Castro" correct="false"/>
            <Reponse id="4" texte="Camilo Cienfuegos" correct="false"/>
        </Reponses>
    </Carte>

    <Carte id="117" difficulte="Moyen" categorieId="2">
        <Question>Quel était le nom du premier empereur de Chine ?</Question>
        <Reponses>
            <Reponse id="1" texte="Qin Shi Huang" correct="true"/>
            <Reponse id="2" texte="Sun Yat-sen" correct="false"/>
            <Reponse id="3" texte="Kangxi" correct="false"/>
            <Reponse id="4" texte="Mao Zedong" correct="false"/>
        </Reponses>
    </Carte>

    <Carte id="118" difficulte="Moyen" categorieId="2">
        <Question>En quelle année a eu lieu la bataille de Waterloo ?</Question>
        <Reponses>
            <Reponse id="1" texte="1815" correct="true"/>
            <Reponse id="2" texte="1805" correct="false"/>
            <Reponse id="3" texte="1812" correct="false"/>
            <Reponse id="4" texte="1820" correct="false"/>
        </Reponses>
    </Carte>

    <!-- Histoire difficile -->

    <Carte id="119" difficulte="Difficile" categorieId="2">
